monitor=,1920x1080@60,auto,1.0
monitor=,preferred,auto,1,mirror,eDP-1


#Samuel = Bill, Zoey, Coach, Rochelle, Hunter, Jockey
#Víctor = Francis, Louis, Common Infected, Special Infected, Charger, Smoker
#Aldo = Ellis, Nick, Spitter, Tank, Witch, Boomer
