# Configuración del tema: Catppuccin-mocha

# GTK
GTK_THEME="catppuccin-mocha-peach-standard+default"
GTK_COLOR_SCHEME="prefer-dark"  # Usamos el valor exacto que entiende gsettings
ICON_THEME="WhiteSur"
CURSOR_THEME="capitaine-cursors"

# Kitty
KITTY_THEME="Catppuccin-mocha"

# Rofi
ROFI_THEME="Catppuccin-mocha"

# Waybar
WAYBAR_THEME="Catppuccin-mocha"

# SwayNC
SWAYNC_THEME="Catppuccin-mocha"

# VSCodium (nombre exacto del tema instalado)
VSCODIUM_THEME="Catppuccin Mocha"

# Spicetify (Spotify)
SPICETIFY_THEME="Sleek"
SPICETIFY_SCHEME="Catppuccin"

# Pywal - Generar colores desde wallpaper
USE_PYWAL="false"  # true o false

# Música del tema
THEME_MUSIC_ENABLED="true"       # true para activar música
THEME_MUSIC_FILE="theme.mp3"      # Nombre del archivo de audio
THEME_MUSIC_VOLUME="0.3"          # Volumen (0.0 a 1.0)

# SWWW (Wallpaper transitions)
SWWW_TRANSITION="center"
SWWW_DURATION="2"
SWWW_FPS="60"
SWWW_BEZIER=".43,1.19,1,.4"
